### PR TITLE
TraderJoe USDT-USDT.e + FRAX-AVAX

### PR DESCRIPTION
**Pull request by pahor167**

### CODE REVIEW

**Comment by MirthFutures** [comment]
@pahor167 When you submit PR for new vaults. You should put the vault and strategy addresses in the comment.

**Comment by MirthFutures** [comment]
There is no liquidity from AVAX to USDT. This strategy will not work, You need to have the proper routing. It should be AVAX -> USDTe -> USDT.

**Comment by pahor167** [comment]
> @pahor167 When you submit PR for new vaults. You should put the vault and strategy addresses in the comment.

Thanks, I will know for next time - 

USDT-USDT.e

Vault: 0xbF3DbFC6ed56D68d0B925D32ea7f6Bfc71a427BA
Strategy: 0xFF9466668d438Dae481DAe22345E656D5709CC8f
Want: 0x74B651Eff97871eA99fcc14423E611d85Eb0EA93
PoolId: 39

FRAX-AVAX

Vault: 0x60a8684f7bde18AeDe01347696AF0DEab5cB587d
Strategy: 0xa633F850b1298d84De7BfEc8644cbeac72A769810xa633F850b1298d84De7BfEc8644cbeac72A76981
Want: 0x862905a82382Db9405a40DCAa8Ee9e8F4af52C89
PoolId: 33

**Comment by pahor167** [comment]
> @pahor167 When you submit PR for new vaults. You should put the vault and strategy addresses in the comment.

Thank you for noticing. I deployed new strategy + vault with fixed configuration. 

USDT-USDTe
Vault: 0x258e9884c111E2e3e0273372521982bd57ef29Bd
Strategy: 0xc729B40Dc115A5470A38AaE71Def4CD5a5cfa096
Want: 0x74B651Eff97871eA99fcc14423E611d85Eb0EA93
PoolId: 39

AVAX-FRAX
Vault: 0x60a8684f7bde18AeDe01347696AF0DEab5cB587d
Strategy: 0xa633F850b1298d84De7BfEc8644cbeac72A76981
Want: 0x862905a82382Db9405a40DCAa8Ee9e8F4af52C89
PoolId: 33

**Comment by pahor167** [comment]
> There is no liquidity from AVAX to USDT. This strategy will not work, You need to have the proper routing. It should be AVAX -> USDTe -> USDT.

Thanks for noticing. I deployed new vault + strategy as follows:

USDT-USDTe
Vault: 0x258e9884c111E2e3e0273372521982bd57ef29Bd
Strategy: 0xc729B40Dc115A5470A38AaE71Def4CD5a5cfa096
Want: 0x74B651Eff97871eA99fcc14423E611d85Eb0EA93
PoolId: 39

AVAX-FRAX
Vault: 0x60a8684f7bde18AeDe01347696AF0DEab5cB587d
Strategy: 0xa633F850b1298d84De7BfEc8644cbeac72A76981
Want: 0x862905a82382Db9405a40DCAa8Ee9e8F4af52C89
PoolId: 33

**Comment by roman-monk** [comment]
shouldn't it be `StrategyTraderJoeDualNonNativeLP` for AVAX-FRAX?
i see there are 2 rewards JOE + FXS, with JOE inactive. 
idk if they tend to activate JOE rewards over time, in this case current strat would require upgrade but `StrategyTraderJoeDualNonNativeLP` would work fine

**Comment by pahor167** [comment]
Since above mentioned PR is merged, I updated strategy to StrategyTraderJoeDualNonNativeLP  and did new deployment 👍 

USDT-USDTe
Vault: 0x258e9884c111E2e3e0273372521982bd57ef29Bd
Strategy: 0xc729B40Dc115A5470A38AaE71Def4CD5a5cfa096
Want: 0x74B651Eff97871eA99fcc14423E611d85Eb0EA93
PoolId: 39

AVAX-FRAX
Vault: 0xd2D0Cf1675961357AfC934856421D2C5ffd87b1e
Strategy: 0xdE6590ee7fde7b1d615894Bc6876e73a46c3D852
Want: 0x862905a82382Db9405a40DCAa8Ee9e8F4af52C89
PoolId: 33

**Comment by MirthFutures** [comment]
> 0xdE6590ee7fde7b1d615894Bc6876e73a46c3D852

Can you verify the contract?

**Comment by pahor167** [comment]
> 0xdE6590ee7fde7b1d615894Bc6876e73a46c3D852

Contract 0xdE6590ee7fde7b1d615894Bc6876e73a46c3D852 is verified

**Pull request merged**
