### PR TITLE
Add 12 Pancake Pools + 1 Kebab

### PR DESCRIPTION
**Pull request by MirthFutures**
Vault - 0x922f8807E781739DDefEe51df990457B522cBCf5
Strategy - 0x1198f78efd67DFc917510aaA07d49545f4B24f11
Pool ID - 69
LP - 0xeB325a8ea1c5abf40c7ceAf645596c1F943d0948

### CODE REVIEW

**Comment by roman-monk** [comment]
Strat needs to use CAKE-BUSD-LINA routing, no liquidity for LINA-BNB

**Comment by MirthFutures** [comment]
ZEE BNB
Vault - 0x29C4C22eC7dF7e936Cb3e6C4A7E5eAE751C7d86B
Strat - 0xc34b9c9DBB39Be0Ef850170127A7b4283484f804
PoolID = 74
LP - 0xB5Ab3996808c7e489DCDc0f1Af2AB212ae0059aF

BRY BNB
Vault = 0x578C066b5c7289f8Ba7c4DB43c110F19D7c51E03
Strat = 0xF9eBb381dC153D0966B2BaEe776de2F400405755
PoolId = 75
LP - 0x5E3CD27F36932Bc0314aC4e2510585798C34a2fC

**Comment by roman-monk** [comment]
@MirthFutures please check preview, it's not working
Preview: https://beefy-app-git-fork-mirthfutures-master.beefyfinance.vercel.app

**Comment by MirthFutures** [comment]
> @MirthFutures please check preview, it's not working
> Preview: https://beefy-app-git-fork-mirthfutures-master.beefyfinance.vercel.app

Working now.

**Comment by roman-monk** [comment]
> > @MirthFutures please check preview, it's not working
> > Preview: https://beefy-app-git-fork-mirthfutures-master.beefyfinance.vercel.app
> 
> Working now.

ok, last thing missed is harvest() call for all vaults, to make sure routing is good.
i've no idea where cake-busd liquidity is coming from? is it safer to use cake-bnb-busd-lina?

**Comment by MirthFutures** [comment]
> > > @MirthFutures please check preview, it's not working
> > > Preview: https://beefy-app-git-fork-mirthfutures-master.beefyfinance.vercel.app
> > 
> > 
> > Working now.
> 
> ok, last thing missed is harvest() call for all vaults, to make sure routing is good.
> i've no idea where cake-busd liquidity is coming from? is it safer to use cake-bnb-busd-lina?

Deployed new strat with a new vault and tested harvest. 

Vault = 0x149f3dDeB5FF9bE7342D07C35D6dA19Df3F790af
Strat = 0x66be88070D38d9F8eE96913aeDF1709ED35aB29A

**Pull request closed without merging**
