### PR TITLE
More Spooky pools

### PR DESCRIPTION
**Pull request by BrknRobot**
FTM-ICE
vault: 0x33E0Feb374C9B7fC3Ac392140BdE3036263D8e5e
strat: 0x8F35521cf1B9145E2C5231B8B3E1c3AEadDc4027

FTM-BADGER
vault: 0x9344e006518af9739F4077014F8B7794777Ae96F
strat: 0xa6914AbA898D613152DB7D338381d53b5Eae0C1d

FTM-BAND
vault: 0xf2e4C5b0Ed40716cB23cCE7eBd15ECDCDa934EDf
strat: 0x3464ab12F2c2fe3DAa90Aa7D90DDe6BA470422BD

FTM-SUSHI
vault: 0xb8c90D7C60Cf88915BCc4F388F207D5F7fDaA9b4
strat: 0x3C180c415332999Fa7e5a65E8490A57fe8Fd7fdb

### CODE REVIEW

**Comment by roman-monk** [comment]
> Optimizer: 800 runs

it's 200 by default.

@MirthFutures please help to check as a Spooky expert 🙏

**Comment by MirthFutures** [comment]
> > Optimizer: 800 runs
> 
> it's 200 by default.
> 
> @MirthFutures please help to check as a Spooky expert 🙏
> 

So for FTMScan you have to make sure the abi-encoded constuctor matches. The constructor FTMScan pulls automatically usually isn't correct. 

Also, optimization is default 200 unless you changed it. 

Also for ease of users can you label the vaults TOKEN-FTM LP instead of FTM-TOKEN LP?

**Comment by nloewen** [comment]
Token labels are flipped, and contracts are verified :+1:

**Comment by MirthFutures** [comment]
These Vaults do not have Panic and Unpaused tested.

**Pull request merged**
