### PR TITLE
Strategy: Fix UST-MATIC LP

### PR DESCRIPTION
**Pull request by shadoweddev**

### CODE REVIEW

**Comment by MirthFutures** [comment]
Vault was never test harvested, it also needs to be set to harvest on deposit.

**Comment by shadoweddev** [comment]
I addressed both of these issues and have created a [PR in beefy.app](https://github.com/beefyfinance/beefy-api/pull/569) to add the new token and updated the corresponding pool in the frontend.

**Comment by roman-monk** [comment]
crashes without wormhole image. 
obv we can't use WORMHOLE asset, its unrelated to UST.
not sure whats better UST or USTw, maybe USTw to differentiate 2 different tokens, so we would need to copy-paste UST image

**Comment by shadoweddev** [comment]
changed to use UST image to fix crash. renamed LP to USTw-MATIC.

**Comment by MirthFutures** [comment]
Resolve conflicts please

**Comment by shadoweddev** [comment]
> Resolve conflicts please

resolved.

**Pull request merged**
