### PR TITLE
Add Stargate avax 

### PR DESCRIPTION
**Pull request by andreb0x**
USDC 
wantAddr =  "0x1205f31718499dBf1fCa446663B532Ef87481fe1"
vaultAddr = "0x79F26046D122d2F26B1D37237D5C056fB580447A"
stratAddr = "0x3871E20e08ae59bDa4b42A1a6C27403bEedDa042"

USDT 
wantAddr =  "0x29e38769f23701A2e4A8Ef0492e19dA4604Be62c"
vaultAddr = "0xA27BF4d56870A37e37a687B8ab3740d8487Ee2C6"
stratAddr = "0x0c326F2e869ae301628540C540633c5D25c7f40a"

### CODE REVIEW

**Comment by andreb0x** [comment]
new strat address: 0x0c326F2e869ae301628540C540633c5D25c7f40a
pending call to "upgrade strat"

**Comment by andreb0x** [comment]
avax USDT: pending first harvest

**Comment by andreb0x** [comment]
avax USDT: pending ownership transfer

**Comment by andreb0x** [comment]
Screen Shot 2022-04-03 at 8 07 02 AM

**Comment by MirthFutures** [comment]
> Screen Shot 2022-04-03 at 8 07 02 AM
>  

Please look at how this is implemented with the deployed vaults and match. Also you need changes on the API. Please look at my fix yesterday.

**Comment by andreb0x** [comment]
API PR: https://github.com/beefyfinance/beefy-api/pull/724

**Comment by andreb0x** [comment]
> > Screen Shot 2022-04-03 at 8 07 02 AM
> 
> Please look at how this is implemented with the deployed vaults and match. Also you need changes on the API. Please look at my fix yesterday.

@MirthFutures will this resolve once API is merged, or do I need to make a USDC.png file? I see a USDC.svg file.

**Comment by pumpingGhost** [comment]
You need to link the image resources manually in your vault entries here like this:
`logo: 'single-assets/USDC.svg', `

This is independent of the api.

**Comment by andreb0x** [comment]
Screen Shot 2022-04-05 at 10 44 02 AM

**Comment by andreb0x** [comment]
Screen Shot 2022-04-07 at 12 41 28 PM
@MirthFutures rejoice

**Pull request merged**
