### PR TITLE
Added Bsc Mdex Vaults: USDT-USDC USDT-BUSD RABBIT-BUSD USDT-BTCB

### PR DESCRIPTION
**Pull request by 0xww**
mooMdexRABBIT-BUSD
Vault: https://bscscan.com/address/0x9deFc3A2c49ed9Eb1Aa85b3baa68D06cE0e8e409#code
Strategy: https://bscscan.com/address/0xED217130964cC7ADb5a63aFB1f98c2d32343E33a#code

mooMdexUSDT-BUSD
Vault: https://bscscan.com/address/0xe6A719ed10a06E01D47f050a7bAE9C4E5129D56A#code
Strategy: https://bscscan.com/address/0x1B4C80Da790eeb2a432E3f401f12266554a2184B#code

mooMdexUSDT-USDC
Vault: https://bscscan.com/address/0x6b115fEC98396fe153bdcA7716EB63779E9936B0#code
Strategy: https://bscscan.com/address/0xe4655CFf2fe56dB15ae4A082d6D4DFd9fC22914e#code

Beefy API PR:
https://github.com/beefyfinance/beefy-api/pull/352

---

mooMdexUSDT-BTCB
Vault: https://bscscan.com/address/0x2E2d0F1bE3AB071EAb2B66C5009846dC21AF9966#code
Strategy: https://bscscan.com/address/0x9544D467e249922C6EE64Ec2da613a2b923D2991#code

Beefy API PR: 

https://github.com/beefyfinance/beefy-api/pull/376

### CODE REVIEW

**Comment by roman-monk** [comment]
no sense to add "-bsc" to the mooToken, as token is already belong to bsc

**Review by roman-monk — CHANGES_REQUESTED** [review]
1) no need "-bsc" in mooToken name
2) vaults should be added below maxi, boost and cakev2
3) wrong routing, there is no MDX-USDC liquidity
4) mdex strategies have additional `ISwapMining(swapmining).takerWithdraw();` on harvest as Mdex pays trading fees.

**Comment by JordanRaphael** [comment]
Check out this strategy that makes use of the ISwapMining
[Mdex FIL-USDT](https://bscscan.com/address/0xf219cfd4d0d32a3c1204fd7323e0acfdd505302f#code)

**Comment by 0xww** [comment]
thanks now I am checking that

**Comment by 0xww** [comment]
### Changes done
vaults remades, setting new strategy with ISwapMining:
- USDT-USDC
- USDT-BUSD
- RABBIT-BUSD

new vault added
- USDT-BTCB

**Comment by 0xww** [comment]
.

**Pull request merged**
