### PR TITLE
Add pSWAMP single

### PR DESCRIPTION
**Pull request by exleyk**
Vault: 0x0974202a9ED632a8061d9960C4Ea3B23E6819518
Strategy: 0xcCA3785ebC40395A2C963AfE967B00D835Bb8d8E

### CODE REVIEW

**Comment by roman-monk** [comment]
no need WMATIC and WMATIC-SWAMP images, just rename it to `MATIC` and can remove `logo` from pool

**Comment by roman-monk** [comment]
will also look more nicely if it's pSWAMP-MATIC (and same order for assets)

**Comment by wivern-co-uk** [comment]
@exleyk it would be great if you can work locally and then push changes in a batch to do not burn build minutes.

**Comment by exleyk** [comment]
Changing the asset pSWAMP to SWAMP in the polygon pool has broken the app, reverting changes.

**Comment by MirthFutures** [comment]
I advise you remove the other vaults and we start with just pSWAMP. It's easier to launch your first vault and we can go from there.

**Comment by roman-monk** [comment]
`balanceOfPool()` is incorrect in strat, as it returns amount of shares but not the actual balance.
it is super critical for non-native LPs, but probably will work for swamp lps if they dont have fees.
but i think it still much safer to use correct way to get balance from autofarm-based contracts - `stakedWantTotal()`

**Comment by exleyk** [comment]
Updated the strat to use `stakedWantTokens()` instead of `userInfo()`. I hope this is what you mean?

swamp-pswamp
New Vault: [0x1CEBC6AB865205ed0abac029ABA500C50c5680B1](https://polygonscan.com/address/0x1cebc6ab865205ed0abac029aba500c50c5680b1)
New Strat: [0x6366614d9EDAB6085C9F934859655A40f33625Ec](https://polygonscan.com/address/0x6366614d9edab6085c9f934859655a40f33625ec)

**Comment by roman-monk** [comment]
@exleyk maybe close? 😅
no tvl

**Pull request closed without merging**
