### PR TITLE
[WIP] New vault page

### LINKED ISSUE #58: Create a separate page for each vault. ($500 Bounty)
Having a routable page to a vault would help us in a few ways.

1. Deep linking will make it easier to get traction and direct users exactly to a vault that they might be interested.
2. Have more space for relevant info. We could add information relating to impermanent loss for example on LP vaults.
3. Be able to do more queries once we're inside the vault page without concern for doing too many concurrent queries.

### PR DESCRIPTION
**Pull request by FloorLamp**
This creates a new route under `/vault/:vaultId` for vault details and actions. Each pool summary on the vaults page is now a link.

Closes #58

### CODE REVIEW

**Comment by superbeefyboy** [comment]
You can mark it as a draft while you are working on it FloorLamp :)

**Comment by DefiDebauchery** [comment]
Would it make more sense to keep the routing, but show this as a modal rather than an actual navigation page?

This way people can click around without having to go back and forth in history, especially with the main page being as heavy as it is.

**Comment by FloorLamp** [comment]
I tried this as a modal initially:

https://cdn.discordapp.com/attachments/758368074968858645/813002704842391562/Screen_Shot_2021-02-21_at_17.55.21.png

The disadvantage of using a modal is that it's not super mobile friendly. Having a separate page also allows for more vault specific queries to be run.

Another idea is to move the vaults list to a drawer on the left, and show vault details on the right. Not sure if this is great on mobile either though.

**Comment by roman-monk** [comment]
@DefiDebauchery yes, i think we can discuss it
https://discord.com/channels/755231190134554696/758368074968858645/813011504009576458

**Comment by roman-monk** [comment]
Hi @FloorLamp 
Soon we gonna have V2 UI https://vote.beefy.finance/#/beefy/proposal/QmUmnXWJwDQwTDehqdGZAtfwFPHKc2zu6VVs58kfyNpaLZ
And it might be not needed to change vaults behaviour now, as it's gonna be changed soon again.
I'm talking about debates should we open dialog, or keep expanded/collapsed, or add animations.

But separate vault page with deeplink is very cool, as we can share it.
So, what if we drop all changes and only keep routing one "vault/:vaultId".
And have a vault page that is 1:1 current vault card + back to the vaults button.

I think we will close issue then.

**Pull request closed without merging**
