### PR TITLE
WIP: Add quickswap tel eth vault

### PR DESCRIPTION
**Pull request by prevostc**
QuickSwap TEL-ETH
```
Vault: 0x3a5252cED60Dc299f4Cc037cF4a6DCD90609D7F7
Strategy: 0x0BDa2aA1D590C7E8C41BFE17d54f2d85866DF1e5
Want: 0xFc2fC983a411C4B1E238f7Eb949308CF0218C750
```

### CODE REVIEW

**Comment by andreb0x** [comment]
make sure you add contract addresses to your PR (see other PRs adding vaults)

**Comment by andreb0x** [comment]
did you use the following script to generate timestamp?
https://github.com/beefyfinance/beefy-app/blob/master/scripts/getPoolCreationTimestamp.js

**Comment by prevostc** [comment]
> did you use the following script to generate timestamp? https://github.com/beefyfinance/beefy-app/blob/master/scripts/getPoolCreationTimestamp.js

fixed

**Comment by prevostc** [comment]
As this was a learning PR, I'm closing it as we don't want to add support for this vault

**Pull request closed without merging**
