### PR TITLE
Add MDX Single BSC/HECO

### PR DESCRIPTION
**Pull request by MirthFutures**
MDX Single
Vault = 0xc34C7923B73eB68E363AaEB2b7fbBeC11Cf90884
Strat = 0xcC3aC47Fd871717DbbFbC669803086cC18e2b898
PoolId = 4
Want = 0x9C65AB58d8d978DB963e63f2bfB7121627e3a739
MC = 0x6aEE12e5Eb987B3bE1BA8e621BE7C4804925bA68

Heco-MDX Single 
Vault = 0xfABDB29A8C1AE335bC65A7505311F8A48223eFaA
Strat = 0x38086c829017621561Ac7d38501988E3A6152A0E
PoolId = 0
Want = 0x25D2e80cB6B86881Fd7e07dd263Fb79f4AbE033c
MC = 0x19D054836192200c71EEc12Bc9f255b1faE8eE80MDX Single
Vault = 0xc34C7923B73eB68E363AaEB2b7fbBeC11Cf90884
Strat = 0xcC3aC47Fd871717DbbFbC669803086cC18e2b898
PoolId = 4
Want = 0x9C65AB58d8d978DB963e63f2bfB7121627e3a739
MC = 0x6aEE12e5Eb987B3bE1BA8e621BE7C4804925bA68

Heco-MDX Single 
Vault = 0xfABDB29A8C1AE335bC65A7505311F8A48223eFaA
Strat = 0x38086c829017621561Ac7d38501988E3A6152A0E
PoolId = 0
Want = 0x25D2e80cB6B86881Fd7e07dd263Fb79f4AbE033c
MC = 0x19D054836192200c71EEc12Bc9f255b1faE8eE80

### CODE REVIEW

**Comment by roman-monk** [comment]
Heco strat is not verified
+ small conflict probably after maxi

**Comment by MirthFutures** [comment]
> Heco strat is not verified + small conflict probably after maxi

Thanks verified and resolved conflict.

**Comment by roman-monk** [comment]
something must be broken, can't build app

**Comment by MirthFutures** [comment]
> something must be broken, can't build app

lol fixed parse error

**Pull request merged**
