### PR TITLE
Beefy API cache busting

### LINKED ISSUE #481: API Cache Busting: GitHub API rate limit issues
RE: https://github.com/beefyfinance/beefy-app/issues/415 / https://github.com/beefyfinance/beefy-app/pull/422

Unauthenticated GitHub API requests are limited to 60 per hour.

Currently the app is calling the API multiple times per refresh (via fetchPrice, fetchApys). I am seeing 3 requests however a Discord user reported seeing more requests causing them to hit the rate limit really quickly. This may have caused prices/APYs to fail to load (or this might just have been the API starting up)

- GitHub API should be called at most once per page load.
image

### PR DESCRIPTION
**Pull request by ReflectiveChimp**
Resolves #481

~~1. GitHub API has rate limit of 60 requests per hour for unauthenticated requests, this makes sure only 1 request is made per page load (instead of 3x in fetchApys, fetchLPs, fetchTokens).
2. If the GitHub API request fails (whether through rate limiting or for other reasons), fallback to a 60-second (configurable) cache buster. 
3. It takes time from when changes are commited to the prod branch, to when the API is deployed, to when the API has loaded on-chain data; this can result in invalid/incomplete data being cached - these changes delay the use of the latest commit hash as a cache buster until it is 5 minutes old (configurable).~~

Please review :)

### CODE REVIEW

**Comment by roman-monk** [comment]
delay deploy is really great addition!

there was a concern from @superbeefyboy of using  `const now = new Date().getTime() / 1000;` might crash API if it gets too many requests.

**Comment by ReflectiveChimp** [comment]
@roman-monk The time should only used if the request to github fails (which should be rarely / only if the user loads the app more than 60 times in one hour). 

Also the time is further divided by 60 (configurable: `FALLBACK_TIME_SECONDS`) to max out at one uncached request per minute. We can increase this if it ever becomes a problem.

**Comment by ReflectiveChimp** [comment]
Updated to be simple time based cache buster (60 seconds)

**Comment by roman-monk** [comment]
have conflicts sorry, probably after EPS vault with a lot of style cleaning from Monster.
should we go with 5-15min timeframes as superb suggested?

**Comment by ReflectiveChimp** [comment]
That should fix merge conflicts.

Regarding the time; I'd tend to agree with @wivern-co-uk that 1 minute will work out fine; given what @superbeefyboy said about how CloudFlare is configured (That it caches the API's response for 15 minutes).

This should mean that the API itself will only be hit once per minute with all further requests being served from the CF cache.

**Pull request merged**
