### PR TITLE
add stella vaults

### PR DESCRIPTION
**Pull request by andreb0x**
// UST-GLMR 
// vaultAddr = "0xb0b90AD6588F3B072Bc4B3E7237189E6AC6808A7"
// stratAddr = "0x9D3b9d52D40778F542F69a2fa0EfC5C2D86Fb687"
// wantAddr =  "0xb6835036C9A2A96D3BfB8DBE1722971fEb456a83"

// DAI-USDC 
// vaultAddr = "0x0b68f9585E24c8D271eFCf60ebd35c1a94A5F91f"
// stratAddr = "0x46B75692C835f93C98800624329E987C0e1BA595"
// wantAddr =  "0x5Ced2f8DD70dc25cbA10ad18c7543Ad9ad5AEeDD"

// BTC-GLMR 
// vaultAddr = "0x721Bf3d97e2E89e12B73D8b40C8B998AF8E0E9a4"
// stratAddr = "0x5b239E0E222200CB48D7fF7cF7D2Fd68Ce948227"
// wantAddr =  "0x4CDf77828b839506bF6B6e219017B65623042400"

// USDC-ETH
// vaultAddr = "0x44f04CA4B29c5F5471345dcaBAB6e40320374bf4"
// stratAddr = "0x79F26046D122d2F26B1D37237D5C056fB580447A"
// wantAddr =  "0x0Aa48bF937ee8F41f1a52D225EF5A6F6961e39FA"

// GLMR-ETH
// vaultAddr = "0x3871E20e08ae59bDa4b42A1a6C27403bEedDa042"
// stratAddr = "0xA27BF4d56870A37e37a687B8ab3740d8487Ee2C6"
// wantAddr =  "0x49a1cC58dCf28D0139dAEa9c18A3ca23108E78B3"

### CODE REVIEW

**Comment by andreb0x** [comment]
pending ownership transfers

**Comment by MirthFutures** [comment]
Make sure in the future to setPendingRewardFunctionName. Also please run creationdate script with include accurate timestamps before I can merge.

**Comment by andreb0x** [comment]
> Make sure in the future to setPendingRewardFunctionName. Also please run creationdate script with include accurate timestamps before I can merge.

where do I find `setPendingRewardFunctionName` ?

**Comment by MirthFutures** [comment]
> > Make sure in the future to setPendingRewardFunctionName. Also please run creationdate script with include accurate timestamps before I can merge.
> 
> where do I find `setPendingRewardFunctionName` ?

On the strategy contract

**Pull request merged**
