### PR TITLE
Fix incorrect balances

### PR DESCRIPTION
**Pull request by JordanRaphael**
That's a follow up PR to #508 . 

Turns out that this line fixes the problem (at least locally). Doesn't sound very confident, but I have no clue why.

Test before merging.

### CODE REVIEW

**Comment by wivern-co-uk** [comment]
> Turns out that this line fixes the problem (at least locally). Doesn't sound very confident, but I have no clue why.

If so, probably there is an issue with initial data: https://github.com/beefyfinance/beefy-app/blob/master/src/features/vault/redux/initialState.js#L14

**Comment by JordanRaphael** [comment]
> > Turns out that this line fixes the problem (at least locally). Doesn't sound very confident, but I have no clue why.
> 
> If so, probably there is an issue with initial data: https://github.com/beefyfinance/beefy-app/blob/master/src/features/vault/redux/initialState.js#L14

Looks like the tokenDecimals it assigns are coming directly from the pool file. Which is always 18.

**Comment by wivern-co-uk** [comment]
> > > Turns out that this line fixes the problem (at least locally). Doesn't sound very confident, but I have no clue why.
> > 
> > 
> > If so, probably there is an issue with initial data: https://github.com/beefyfinance/beefy-app/blob/master/src/features/vault/redux/initialState.js#L14
> 
> Looks like the tokenDecimals it assigns are coming directly from the pool file. Which is always 18.

Yes, you are right, this issue should be fixed in `initialState`, so we specify correct decimals when app starts and not at runtime.

**Comment by JordanRaphael** [comment]
Is the use of token as symbol here: [https://github.com/beefyfinance/beefy-app/blob/master/src/features/vault/redux/initialState.js#L13](https://github.com/beefyfinance/beefy-app/blob/master/src/features/vault/redux/initialState.js#L13) correct?

Taking a look at [https://github.com/beefyfinance/beefy-app/blob/master/src/features/configure/vault/bsc_pools.js#L55](https://github.com/beefyfinance/beefy-app/blob/master/src/features/configure/vault/bsc_pools.js#L55), looks like this value can't be used to distinguish single asset tokens.

Would it be correct to use assets instead of token?

**Comment by ReflectiveChimp** [comment]
@JordanRaphael Can you test this; I think the issue here is just the use of the `tokens` variable overwriting the 'global' one which is why information such as the decimals were missing for the call to `fetchBalances`

https://github.com/ReflectiveChimp/beefy-app/commit/650ca147096b516c79edc1faa511d20709eeb227#diff-f5d88a530399abc1f1b297863b2f6ba64709fffb3f6531915a08b86cbffcb97a

**Comment by JordanRaphael** [comment]
> @JordanRaphael Can you test this; I think the issue here is just the use of the `tokens` variable overwriting the 'global' one which is why information such as the decimals were missing for the call to `fetchBalances`
> 
> [ReflectiveChimp@650ca14#diff-f5d88a530399abc1f1b297863b2f6ba64709fffb3f6531915a08b86cbffcb97a](https://github.com/ReflectiveChimp/beefy-app/commit/650ca147096b516c79edc1faa511d20709eeb227#diff-f5d88a530399abc1f1b297863b2f6ba64709fffb3f6531915a08b86cbffcb97a)
> 
> Specifically the `...tokens[token.symbol],` part was working on the empty local `tokens` variable so wasn't bringing in the rest of the token data.

Just tested but doesn't work for me. Do you want me to try changing the name of tokens in fetchBalances.js as well?

**Comment by wivern-co-uk** [comment]
> Is the use of token as symbol here: https://github.com/beefyfinance/beefy-app/blob/master/src/features/vault/redux/initialState.js#L13 correct?
Yes, that's intentional. See below...

> Taking a look at https://github.com/beefyfinance/beefy-app/blob/master/src/features/configure/vault/bsc_pools.js#L55, looks like this value can't be used to distinguish single asset tokens.
That's legacy, naming in `*_pools.js` is as is. Check for `* LP2` tokens, for example.
 
> Would it be correct to use assets instead of token?
No, assets are not a LP token

**Comment by ReflectiveChimp** [comment]
> Just tested but doesn't work for me. Do you want me to try changing the name of tokens in fetchBalances.js as well?

Ah it fixes some missing information but `tokens[token.symbol]` when `token.symbol` = 'DOGE' is undefined.

This goes back to initialState of vault.tokens which is built from the pools file. DOGE is only there as an LP so is never added to vault.tokens as a single asset.

We could add all tokens from tokenlist.json to vault.tokens however that would make the app fetch/update balances for those tokens all the time; when they are only needed for Zap.

As you found out `token` has the decimals etc needed to pass to balance so I'd be tempted just to combine what we both changed.

https://github.com/ReflectiveChimp/beefy-app/blob/3815dc7171a3350443def27c34579dd6da80121a/src/features/vault/components/PoolDetails/DepositSection/DepositSection.js#L100-L118

- Pass symbol and decimals
- Fill in any existing information from state.vault.tokens[token.symbol]
- Do not overwrite the allowance object while doing the above

**Comment by JordanRaphael** [comment]
> > Just tested but doesn't work for me. Do you want me to try changing the name of tokens in fetchBalances.js as well?
> 
> Ah it fixes some missing information but `tokens[token.symbol]` when `token.symbol` = 'DOGE' is undefined.
> 
> This goes back to initialState of vault.tokens which is built from the pools file. DOGE is only there as an LP so is never added to vault.tokens as a single asset.
> 
> We could add all tokens from tokenlist.json to vault.tokens however that would make the app fetch/update balances for those tokens all the time; when they are only needed for Zap.
> 
> As you found out `token` has the decimals etc needed to pass to balance so I'd be tempted just to combine what we both changed.
> 
> https://github.com/ReflectiveChimp/beefy-app/blob/3815dc7171a3350443def27c34579dd6da80121a/src/features/vault/components/PoolDetails/DepositSection/DepositSection.js#L100-L118
> 
> * Pass symbol and decimals
> * Fill in any existing information from state.vault.tokens[token.symbol]
> * Do not overwrite the allowance object while doing the above

We could wait for some feedback first, if the solution is accepted we can implement it :)

**Comment by MirthFutures** [comment]
Is this still needed

**Comment by JordanRaphael** [comment]
Yes, we had another report of this issue today. This solution does work, if you can push a cleaner one do so or merge this one for now.

**Pull request merged**
