### PR TITLE
Add Geist LINK vault

### PR DESCRIPTION
**Pull request by photonintrique**
Linked API PR: [https://github.com/beefyfinance/beefy-api/pull/564](https://github.com/beefyfinance/beefy-api/pull/564)

### CODE REVIEW

**Comment by MirthFutures** [comment]
No manual testing was done on this vault https://ftmscan.com/address/0x8fb89354463dbb542232835c2b1a4792cc10f315

**Comment by photonintrique** [comment]
Hey @MirthFutures, what kind of manual testing are you expecting on the strategy?
Manual testing was done on the [vault](https://ftmscan.com/address/0x0d46560e9bad07276bffea76936f74a42dfe42e7).

**Comment by sircryptomaxi** [comment]
@photonintrique Manual testing steps are here: https://github.com/beefyfinance/beefy-contracts#3-deploy-the-smart-contracts 
All of steps in the manual testing are required to be completed before the vault can go live. Can you please drop a message on the Beefy discord in #strategy-devs? We can help answer questions and coordinate efforts better there.

**Comment by cyberthornicrofti** [comment]
Hey @MirthFutures + @sircryptomaxi, sorry for the misunderstanding. Redeployed + tested according to the steps in the link you provided.

**Comment by photonintrique** [comment]
Hey @MirthFutures + @sircryptomaxi, sorry for the misunderstanding. Redeployed + tested following the steps on the link provided.

**Comment by roman-monk** [comment]
i dont understand why there are 58 source files in the strategy, including multiple other strategies.
something definitely was done wrong during deployment. 
i prefer if Geist vaults match bytecode of the ones deployed by @sircryptomaxi 

vault bytecode is also confusing, it is unique, but its compiled with the settings i use for deployments, so normally it should just pick up my sources.

**Pull request closed without merging**
