### PR TITLE
Multicall Launchpools

### PR DESCRIPTION
**Pull request by ReflectiveChimp**
## Aims
- Reduce RPC calls for launchpool data
- Reduce number of re-renders

## UI changes
- No flash of page before wallet is connected (will see flash of wallet connect notice while auto connecting instead)
- Launchpool approvals are for unlimited (max uint256), rather than 79228162514 ether.
- Launchpool APRs should load more reliably
- Tidy of single launchpool page, now that we are showing more decimal places to ensure the numbers fit
- Disable Unstake if zero staked
- Disable Claim if zero rewards available
- Disable Claim & Unstake if zero staked or zero rewards available

#### Everything in the store is now an object mapping the launchpool id to a piece of data
e.g. `fetchApprovalPending[id]` is `true|false` depending on whether or not there is a pending approval tx 
#### Only data that changes is saved to the store
Static data of launchpools from e.g. bsc_stake.js are exported from `getNetworkData.js` as `launchpools`, an object keyed to the pool `id`, and is no longer stored as state.
Data that can change is stored in flat maps keyed to the pool `id`  e.g. `userApproval[id]` is the users approval limit for the deposit token / `poolFinish[id]` is the periodFinish timestamp of the launchpool
#### Subscriptions
When a component needs data for a pool, it can subscribe to that data by calling `subscribe` on mount:
e.g. on the single launchpool page, we need all data
```js
const { subscribe } = useLaunchpoolSubscriptions();
useEffect(() => {
  return subscribe(launchpool.id, {
    userApproval: true,
    userBalance: true,
    userStaked: true,
    userRewardsAvailable: true,
    poolStaked: true,
    poolApr: true,
    poolFinish: true,
  });
}, [subscribe, launchpool]);
```
however on the list of launchpools page, we only need the `periodFinish` for active pools:
```js
useEffect(() => {
  return subscribe(id, {
    poolFinish: status !== 'closed',
  });
}, [subscribe, id, status]);
```

`subscribe` returns a function that should be returned from `useEffect`, this makes sure the data is unsubscribed from when the component unmounts.

#### Updating subscriptions
To keep the data required for subscriptions up to date, `useLaunchpoolUpdates` should be called in a component only rendered once per page. 
e.g. in `StakePool` for the single pool page, or `StakePools` for the list page, or `VisiblePools` for the vaults page.
This function takes care of making RPC calls in the background, keeping the data subscribed to up to date. 
Reference counts are used to ensure only the calls required for the subscribed data for the subscribed pools are called.
Defaults to once per 30 seconds.

#### Updating immediately
`fetchApproval`/`fetchClaim`/`fetchExit`/`fetchStake`/`fetchWithdraw` have been modified to call update immediately upon TX receipt.

#### Accessing subscribed data
There is a set of helper functions to get the data required from the state:
`usePoolFinish(id)`: period finish of the pool as a string
`usePoolStatus(id)`: pool status, either `soon`, `active` or `closed`
`usePoolApr(id)`: apr of pool as number, e.g. `0.01` to represent 1%
`usePoolStaked(id)`: total number of tokens staked in the pool (uses `byDecimals`)
`useUserApproval(id)`: how many tokens the user has approved the pool to spend (uses `byDecimals`)
`useUserBalance(id)`: how many tokens are in the users wallet  (uses `byDecimals`)
`useUserStaked(id)`: how many tokens the user had staked in the pool (uses `byDecimals`)
`useUserRewardsAvailable(id)`: how many tokens of the earned token are available for the user to claim (uses `byDecimals`)

#### StakePoolsPool
Represents each pool in the list of pools page
#### StakeCountdown
Counts down to period finish (Limits the rendering of only this component every second)

#### Store
Adds `vaultLaunchpools`, a map of vault id to launchpool id, for those vaults that have an active launchpool.
New reducer `vaultLaunchpoolsReducer` listens for updates of a launchpool's `poolStatus` and updates this map.
#### Components
`VisiblePools` calls `useLaunchpoolUpdates` to ensure subscriptions are updated.
`Pool` subscribes to `poolApr` and `poolFinish` for it's launchpool if there is one.

### CODE REVIEW

**Comment by ReflectiveChimp** [comment]
I think this is ready for review now.

**Comment by roman-monk** [comment]
a lot of great changes! we will need all of this for v2 😅
about approval limit - there might be the case when token has approval limit, XVS token has it, but should be ok for boost as we stake only BIFI and mooTokens.
would you fix conflict, cant do this via github

**Comment by strive-phil** [comment]
Think the conflict was just that fetchPoolsData.js is now deleted.
Merged but can't test until later.

**Comment by ReflectiveChimp** [comment]
Think the conflict was just that fetchPoolsData.js is now deleted.
Merged but can't test until later.

**Pull request merged**
