### PR TITLE
Add QuickSwap PSP-MATIC

### PR DESCRIPTION
**Pull request by pumpingGhost**

### CODE REVIEW

**Comment by pumpingGhost** [comment]
vault: 0x051aBa342824Ba03519694774B4e9297618Fa818
strategy: 0x3da758e2be3183fed8604FE0D23EC22bA15786A2
want: 0x7AfC060acCA7ec6985d982dD85cC62B111CAc7a7

**Comment by sircryptomaxi** [comment]
@pumpingGhost For future reference the callFee should be 11 and `harvestOnDeposit` should be `true` for all vaults on Polygon & Fantom. I will adjust these using the keeper but please do so before transferring ownership next time.

Other than that, LGTM @MirthFutures

**Review by roman-monk — CHANGES_REQUESTED** [review]
polygon app crashes, you should test it locally with `yarn start`

**Comment by pumpingGhost** [comment]
Crash was due to a missing image resource for PSP.
Issue is now fixed.

**Comment by roman-monk** [comment]
Almost!
Buy link is missing and the logo seems to be incorrect, its blue on white

**Comment by pumpingGhost** [comment]
> Almost! Buy link is missing and the logo seems to be incorrect, its blue on white

i took the blue on white logo from their official twitter. The ones linked on coingecko and polygonswap have very poor resolution, that's why I chose to look for a better one on their social media. Should I swap them anyway?

**Pull request merged**
