### PR TITLE
Add optional, platform-specific withdrawal notice

### PR DESCRIPTION
**Pull request by PandaWhisperer**
As per https://discord.com/channels/755231190134554696/758368074968858645/931530169343160350, adds a note for Geist vaults to set gas limit for withdrawal transactions to 9.9M. 

Note is platform-specific and can be customized via translations. 

Screen Shot 2022-01-14 at 10 01 25 AM

### CODE REVIEW

**Comment by AllTradesz** [comment]
As a hack, this is ok if it builds all right. Awaiting approval from @mjoaris that UI is good enough for now.

**Comment by mjoaris** [comment]
Good enough for me, for now 😁 !

**Comment by PandaWhisperer** [comment]
@mjoaris wanted a version that shows the notice in a banner similar to the vault boosts. 

I got it working, but the transition is a bit awkward (and maybe the color is too bright?). Check the video and lmk if that is of interest.

Not sure if I can fix the transition though.

https://user-images.githubusercontent.com/749244/149574138-30d84e51-172f-4791-a826-8878ae2e57ed.mov

**Comment by roman-monk** [comment]
wouldn't it be better to just set gas limit to 9M from the app for Geist withdrawals? 
without requiring anything from user.

app can estimate and manually set gas limit or price, currently it is done by user wallet (Metamask) which multiples estimation by 1.5

**Comment by mjoaris** [comment]
> wouldn't it be better to just set gas limit to 9M from the app for Geist withdrawals? without requiring anything from user.
> 
> app can estimate and manually set gas limit or price, currently it is done by user wallet (Metamask) which multiples estimation by 1.5

Yes! Would be great. DefiDebauchery mentioned this earlier, if we can do that this fix would not be necessary.

**Comment by AllTradesz** [comment]
> wouldn't it be better to just set gas limit to 9M from the app for Geist withdrawals? without requiring anything from user.
> 
> app can estimate and manually set gas limit or price, currently it is done by user wallet (Metamask) which multiples estimation by 1.5

This would naturally be fine too. @mjoaris was after a quick fix of this nature, so we just jumped on it with this, and since this is devved, we can go with it for now, yes?

Gas estimation is a harder problem and fix, I've gathered. A couple of us were looking at similar for v2 and daunted enough that we put it on a back burner.

**Comment by PandaWhisperer** [comment]
@roman-monk that sounds like a great idea, but it does not appear that the web3 hooks in the app currently support setting a custom gas limit. 

This would definitely be a much cleaner solution but it also requires a lot more work while support requests are piling up. And since V2 is due to be released soon anyways, we don't want to invest that much work into the old app.

**Comment by PandaWhisperer** [comment]
Final version screenshots

#### Light theme
Screen Shot 2022-01-15 at 8 10 08 AM

#### Dark theme
Screen Shot 2022-01-15 at 8 10 20 AM

**Comment by AllTradesz** [comment]
LGTM @roman-monk

**Comment by roman-monk** [comment]
> This would definitely be a much cleaner solution but it also requires a lot more work while support requests are piling up. And since V2 is due to be released soon anyways, we don't want to invest that much work into the old app.

i think it requires less work actually, as no UI is needed, and just 1 param in fetchWithdraw which is used only in WithdrawSection.
but you've already done it, so ok 🙂

**Comment by mjoaris** [comment]
I still view this as a bad-aid, short term fix, and I think that setting the gas limit is a much better solution. I hope that will still be explored :)

**Pull request merged**
