### PR TITLE
add stellaswap L1 token pools

### PR DESCRIPTION
**Pull request by andreb0x**
"stellaswap-usdc-ftm"
 vaultAddr = "0x622d8A33d67464596b6612BB2d396a8d7870B536"
 stratAddr = "0xBA061Ff2009905Cb45bABeb3eB7CFb8f97873555"
 wantAddr =  "0x077Fc7B4455050249D7F5511ED588a665E03e6C5"
 
 "stellaswap-wglmr-ftm"
 vaultAddr = "0xbCF6b67A5Cd2642503b92c6367F9F0C592ACA744"
 stratAddr = "0xe9A624096E3dc62d897EE9E9A20c2aF1c364452D"
 wantAddr =  "0x2Afab635EA2DC4B498EF1C00E63b7a7dBa9c93C6"

 "stellaswap-avax-wglmr"
 vaultAddr = "0x016A2b0AA20F595f3d692529d74bF107E394B69f"
 stratAddr = "0xAe6b83c138f84fa9E90CDbCDD105021173c8E579"
 wantAddr =  "0x2F412C140080039eaF9dE01c95e84cFb1c8D98aD"
 
 "stellaswap-matic-wglmr"
 vaultAddr = "0xcA010C39E70Dc625Ec4f10a9f5d7d28d3EAD2703"
 stratAddr = "0x7783d23C0880B553f97f084008b8ab7eE445701F"
 wantAddr =  "0x6775ff3828a19EB5926C0C4D572183cA15Aa4C08"
 
 "stellaswap-luna-wglmr"
 vaultAddr = "0x253f0C0b847d516B49F8481df318d3DEcB048FC5"
 stratAddr = "0x8F8d1dE7f7E2B8C32BABFa1CE21613e8EcB49593"
 wantAddr =  "0xE2BFE2F1437f249B15B7111011219995ecc43155"

### CODE REVIEW

**Comment by MirthFutures** [comment]
Routing is wrong on FTM-USDC. There is no liquidity GLMR-FTM. Also, you need to setPendingRewardName or call reward shows 0.

**Comment by MirthFutures** [comment]
> Routing is wrong on FTM-USDC. There is no liquidity GLMR-FTM. Also, you need to setPendingRewardName or call reward shows 0.

Nevermind, I see the glmr ftm farm. Its always safer to route through the pair.

**Comment by andreb0x** [comment]
https://github.com/beefyfinance/beefy-contracts/pull/165/commits/0512823fafe92f67581a4e53f8c7912e699b2656

**Comment by MirthFutures** [comment]
> [beefyfinance/beefy-contracts@0512823](https://github.com/beefyfinance/beefy-contracts/commit/0512823fafe92f67581a4e53f8c7912e699b2656)

Please add correct creationdate timestamps and push again

**Pull request merged**
