### PR TITLE
Pools: add missing platforms, checksum addresses, MDex -> Mdex etc

### PR DESCRIPTION
**Pull request by ReflectiveChimp**
- validatePools.js: add check for missing platform or tokenDescription in *_pools.js
- validatePools.js: add check for checksummed addresses in *_pools.js ('tokenAddress', 'earnedTokenAddress', 'earnContractAddress')
- validatePools.js: do not skip checking the rest of the pool fields for venus-wbnb
- validatePools.js: add --platform-summary cli argument (see below)
- remove zero-width spaces from DRUGS token in bsc_pools.js
- use 'Mdex' rather than 'MDex' in bsc_pools.js
- use checksummed addresses (avax: 5, bsc: 35, heco: 1, polygon: 5) in *_pools.js
- add missing `platform:` keys (bsc: 97, heco: 1, fantom: 1) in *_pools.js

`yarn run validate --platform-summary` will do usual checks but also output a list of platforms per chain (useful for checking they are consistently named)
e.g.
```
Validating 22 pools in fantomPools...
Platforms:
        Beefy.Finance (1)
        Ester (2)
        Froyo (2)
        SpookySwap (17)
Active pools: 22/22
```

_adds @ethersproject/address as dev dependency_

### CODE REVIEW

**Comment by roman-monk** [comment]
can we revert all bsc_pools platforms please? 😅
i intentionally removed most of them (all degens) where we have only 1 token + bnb/busd to not show in filter.
i dont think we need there ramen, salt, yieldbay etc, they can be filtered by token name.

also all new 'Pancake' are not really Pancake platform (they just use Pancake LPs which we set in token description), only PCS farms are Pancake platform

**Comment by ReflectiveChimp** [comment]
@roman-monk Is there a reason we don't want some platforms appearing in the UI? (Surely if we farm the platform is should appear?)

If we really do need a way to exclude some platforms from the filter (/only include a set list); can we come up with another way to do so other than omitting the `platform:` key? I'd like the validatePools script to force this to be filled in as some pools that definitely should be in the filter have been added without one.

Re: Pancake - I'll go through them and try figure out what the platform should actually be.

**Comment by roman-monk** [comment]
> @roman-monk Is there a reason we don't want some platforms appearing in the UI? (Surely if we farm the platform is should appear?)

yes, it doesn't help users when they see long list of platforms most of them they've never heard about and very likely not interested.
i suggest to just remove all platform that you've added and do not validate them.
there was only 1 case when we lost platform - single Mdex. 
except this we didn't have any issues, that's why i think we can resolve them manually

**Comment by roman-monk** [comment]
can suggest "Degen" platform as a compromise 😄

**Comment by ReflectiveChimp** [comment]
@roman-monk Maybe just 'Other' ?

BillionHappiness (2)

**Comment by ReflectiveChimp** [comment]
@roman-monk Maybe just 'Other'?

Can we confirm we don't want to keep any of the following? Happy to replace them all with 'Other'.

BillionHappiness (2)
CafeSwap (3)
Complus (1)
ForTube (5)
FryWorld (2)
Marshmallow (6)
Narwhal (1)
Nyanswop (1)
PantherSwap (2)
Pumpy (1)
RamenSwap (2)
SaltSwap (2)
SlimeFinance (2)
Sponge (3)
Squirrel (1)
ThunderSwap (2)
Traphouse (18)
YieldBay (3)

**Comment by roman-monk** [comment]
> Can we confirm we don't want to keep any of the following? Happy to replace them all with 'Other'.

would be great 👍

**Comment by ReflectiveChimp** [comment]
**Global platform: changes**
_As discussed above_

PantherSwap -> Other
BillionHappiness -> Other
Marshmallow -> Other
YieldBay -> Other
ThunderSwap -> Other
Pumpy -> Other
Complus -> Other
SlimeFinance -> Other
Sponge -> Other
SaltSwap -> Other
RamenSwap -> Other
CafeSwap -> Other
Nyanswop -> Other
Traphouse -> Other
Narwhal -> Other
ForTube -> Other
FryWorld -> Other

**Vault platform: changes**
hps-hps-bnb: JulSwap -> Other _(JulSwap LP but farm is on BillionHappiness)_

**Vault tokenDescription: changes**
_Changed to follow the LP Provider (Farm Provider) format used elsewhere e.g. Mdex (Auto)_

garuda-garuda-usdc: Pancake -> Pancake (Garuda)
grand-grand: Pancake -> Grand
grand-grand-bnb: Pancake -> Pancake (Grand)
dumpling-sdump-bnb: Pancake -> Pancake (Dumpling)
dumpling-sdump-busd: Pancake -> Pancake (Dumpling)
satis-xsat-busd: Pancake -> Pancake (Statis)
satis-xsat-bnb: Pancake -> Pancake (Statis)
garuda-garuda-usdt: Pancake -> Pancake (Garuda)
ica-ica-btcb-eol: Pancake -> Pancake (Icarus)
ica-ica-eth-eol: Pancake -> Pancake (Icarus)
zefiv2-zefi-bnb: Pancake -> Pancake (ZCore)
zefiv2-zefi-busd: Pancake -> Pancake (ZCore)
satis-sat-bnb-eol: Pancake -> Pancake (Statis)
satis-sat-busd-eol: Pancake -> Pancake (Statis)
typhv2-typh-bnb: Pancake -> Pancake (Typhoon)
typh-typh-bnb: Pancake -> Pancake (Typhoon)
biti-biti-bnb: Pancake -> Pancake (Biti)
bingo-bgo-busd: Pancake -> Pancake (Bingo)
bingo-sbgo-busd: Pancake -> Pancake (Bingo)
swirl-swirl-bnb: Pancake -> Pancake (Swirl)
zefi-zefi-bnb: Pancake -> Pancake (ZCore)
zefi-zefi-busd: Pancake -> Pancake (ZCore)
hps-hps-bnb: JulSwap -> JulSwap (BillionHappiness)
squirrel-nuts-bnb-eol: Pancake -> Pancake (Squirrel)
memefarm-ape-bnb: Pancake -> Pancake (MemeFarm)
memefarm-mfrm-bnb: Pancake -> Pancake (MemeFarm)
soup-soup-bnb: Pancake -> Pancake (Soup)
soup-soups-bnb: Pancake -> Pancake (Soup)
crow-crow-busd: Pancake -> Pancake (Crow)
crow-crow-bnb: Pancake -> Pancake (Crow)
monster-msc-busd: Pancake -> Pancake (Monster)
monster-msc-bnb: Pancake -> Pancake (Monster)
cake-bts-busd: Pancake -> Pancake (Bolt)
cake-btd-busd: Pancake -> Pancake (Bolt)
monster-mss-busd: Pancake -> Pancake (Monster)
cake-bdo-bnb-sbdo: Pancake -> Pancake (bDollar)
cake-bdo-bnb-old: Pancake -> Pancake (bDollar)
cake-sbdo-busd: Pancake -> Pancake (bDollar)
cake-bdo-busd: Pancake -> Pancake (bDollar)

**Comment by ReflectiveChimp** [comment]
Via Discord:
Pancake -> PancakeSwap in tokenDescription and platform
Auto -> Autofarm in tokenDescription

**Pull request merged**
