### PR TITLE
Per chain page titles

### PR DESCRIPTION
**Pull request by ReflectiveChimp**
Uses `react-helmet` to add per chain / per page titles.

`{{networkName}}` below is configurable via the following object:
`const networkFriendlyName = {
  56: 'BSC',
  128: 'HECO',
  43114: 'AVAX',
  137: 'Polygon',
  250: 'Fantom',
};`

Page meta is defined in getPageMeta.js - with helpers to translate strings or append " | Beefy Finance" to titles:
```
const PAGE_META = {
  'App-Meta-Title': ({ networkName }) => appendTitle(`${networkName}`),
  'Vault-Meta-Title': ({ vaultName, vaultDescription, networkName }) =>
    appendTitle(`${vaultName} - ${vaultDescription} - ${networkName}`),
  'App-Meta-Description': translate,
  'Stakes-Meta-Title': translateAppendTitle,
  'Stake-Meta-Title': translateAppendTitle,
};
```

Non-translatable meta:

``"App-Meta-Title":`${networkName}`,``
e.g. **BSC | Beefy Finance**
Used as the title for the main app page (list of vaults) / as a fallback
_Available placeholders:_
`{{networkName}}` - e.g. BSC/HECO/AVAX/Polygon/Fantom

``"Vault-Meta-Title": `${vaultName} - ${vaultDescription} - ${networkName}`,``
e.g. **IRON-BUSD LP - Pancake - BSC | Beefy Finance**
The title of a single vault page
_Available placeholders:_
`{{networkName}}` - e.g. BSC/HECO/AVAX/Polygon/Fantom
`{{vaultName}}` - e.g. IRON-BUSD LP
`{{vaultDescription}}` - e.g. Pancake

Translatable meta (see translation.json):

`"App-Meta-Description": "The Multichain Yield Optimizer",`
e.g. **The Multichain Yield Optimizer**
The meta description used for the app. Passing `{{networkName}}` here but currently unused.
_Available placeholders:_
`{{networkName}}` - e.g. BSC/HECO/AVAX/Polygon/Fantom

`"Stakes-Meta-Title": "Boosts - {{networkName}}",`
e.g. **Boosts - BSC | Beefy Finance**
The title of the Launchpool / Boosts page
_Available placeholders:_
`{{networkName}}` - e.g. BSC/HECO/AVAX/Polygon/Fantom

`"Stake-Meta-Title": "Earn {{earnedToken}} - Boosted by {{boostedBy}} - {{networkName}}",`
eg. **Earn DOP - Boosted by Dopple Finance - BSC | Beefy Finance**
_Available placeholders:_
`{{networkName}}` - e.g. BSC/HECO/AVAX/Polygon/Fantom
`{{earnedToken}}` - e.g. DOP
`{{boostedBy}}` - e.g. Dopple Finance

Notes:
- This PR also moves/renames `getTxUrl` to `getNetworkTxUrl`
- My IDE auto-formatted the files I edited - I can undo these changes if it is a problem.

### CODE REVIEW

**Comment by PCRyan** [comment]
Aren't the following localization-items superfluous and best not to add?
`"App-Meta-Title": "{{networkName}} - Beefy Finance",`
`"Vault-Meta-Title": "{{vaultName}} - {{vaultDescription}} - {{networkName}} - Beefy Finance",`
in that we are unlikely to ever want "Beefy Finance" translated, right, given that it's our brand, so to speak?
And if that's the case, we should remove the `- Beefy Finance` parts within these strings altogether.  WDYT?

**Comment by ReflectiveChimp** [comment]
@PCRyan Good shout - I've moved the 'Beefy Finance' part out in to a title template instead.

The title will now be the string from the translation file follow by ` | Beefy Finance` - I've updated my original comment to reflect this.

I've left the rest in as although I agree in principle that there is nothing to translate for `App-Meta-Title` or `Vault-Meta-Title`; the strings need to be defined somewhere and it's possible that we may want to change them now or in the future to something similar to how `Stake-Meta-Title` is written.

**Comment by PCRyan** [comment]
@ReflectiveChimp Thanks for the reply. However I am seeing this from the standpoint of localization workflow to translators, and so feel right to resist confusing that workflow. Having some strings in translations.json with no need to be localized does that, one way or another. So I would request that another way/place to abstract these strings be implemented instead. A different JSON file, constants, function or macro implementing a layered locate, any or a mixture of these as fits the situation. I hope not too much to ask, and that I'm still in my lane to do so.

**Comment by ReflectiveChimp** [comment]
@PCRyan How's that for you?

Bit confusing to add / change meta now however that should need done less than translations.

**Comment by PCRyan** [comment]
Very much appreciated! Glad you could accommodate.

**Pull request merged**
