### PR TITLE
Pool avax pangolin lost avax

### PR DESCRIPTION
**Pull request by FuntasticMrFox**
Pool Avalanche Pangolin LOST-AVAX (redeployed)

Vault: 0x02BE142346cbCAf2A1d8A8F7B4a5F2d929259270
Strategy: 0xFDF3BeD653d15825368A5f57547b246ef22f9B5e
Want: 0x8461681211B49c15e20B3Cfd4c63BE258878B7D9
Pool ID: 105

PR beefy-contracts: #184
PR beefy-app: beefyfinance/beefy-app#1183
PR beefy-beefyfinance/beefy-api#754

### CODE REVIEW

**Comment by sircryptomaxi** [comment]
@FuntasticMrFox strategy owner is incorrect, you've transferred it to the vault timelock instead of strategy timelock. I'll put forward a multi-sig tx to get that transferred. Vault owner is not transferred yet, please confirm addresses in the address book of the API and tranfer ownership of vault

**Comment by FuntasticMrFox** [comment]
@sircryptomaxi sorry about that, i transfered ownership of vault https://snowtrace.io/tx/0x7954e4dc1098921da9932afbad3a7038f5b509bdb673e81a5525013209e244c6. Thank you to put a forward a multisig tx.

**Comment by roman-monk** [comment]
seems wrong rewardToOutput route, it swaps to native

**Comment by FuntasticMrFox** [comment]
> seems wrong rewardToOutput route, it swaps to native

Fixed

**Pull request merged**
