### PR TITLE
Strategy: WETH.e-AVAX

### PR DESCRIPTION
**Pull request by AABeely**
Vault: 0x95F8F990a0c439Dfd5c90Df255aCa869fE860C02
Strategy: 0xa2b4FbE20373F38ebbB2281D809e672Dc99A9686
Want: 0x7c05d54fc5CB6e4Ad87c6f5db3b807C94bB89c52

### CODE REVIEW

**Comment by sircryptomaxi** [comment]
@AABeely can you please submit similar vaults together at the same time on the same PR rather than individually. We have limited amount of build minutes and git conflicts are less likely to come up that way.

**Comment by AABeely** [comment]
My bad, I'll make sure all the ones to follow are batched up together

**Comment by MirthFutures** [comment]
Same issue with this one. Please change to keep harvest function consistent.

**Comment by AABeely** [comment]
Closing this merge request to merge it with the wider PangolinV2 work

**Pull request closed without merging**
