### PR TITLE
sushi-usdc-bct sushi-bct-klima

### PR DESCRIPTION
**Pull request by Moonster-BSC**
sushi-usdc-bct

Vault: 0x90A7289A3aAb4b070A2646DCa757025Ee84cF580
Strategy: 0x1F9871133c8E093e9e1E2815Ca76B75CC7bB8c11
Want: 0x1E67124681b402064CD0ABE8ed1B5c79D2e02f64
PoolId: 50

sushi-bct-klima

Vault: 0x19AfD39F0f8A2deeD37Ed74F6a126b68432D4bc7
Strategy: 0x825B726fc5DEb89b42352458C28f9F2ce20AEc13
Want: 0x9803c7aE526049210a1725F7487AF26fE2c24614
PoolId: 49

### CODE REVIEW

**Comment by MirthFutures** [comment]
@Moonster-BSC Are these old strats? Polygon should be harvestOnDeposit.

**Comment by MirthFutures** [comment]
They also don't have the harvester infra

**Comment by Moonster-BSC** [comment]
> @Moonster-BSC Are these old strats? Polygon should be harvestOnDeposit.

You're right, I'll. update in contracts repo and redeploy

**Comment by Moonster-BSC** [comment]
@MirthFutures Fixed the addresses to point to the updated contracts.

**Pull request merged**
