### PR TITLE
add ETH-ETH stablePool on stellaswap

### PR DESCRIPTION
**Pull request by lodelux**
Vault: 0xdd856F58E8B01579ef5DbE78f597615D66c320EE
Strategy: 0x4467f78F9054570d3eC811a2FDA5186b6D24b252
Want: 0xa3eE3a0a36Dc915fDc93062e4B386DF37d00217E
PoolId: 8

https://github.com/beefyfinance/beefy-api/pull/808

### CODE REVIEW

**Comment by sircryptomaxi** [comment]
CallReward is 0? Is something broken there?

**Comment by lodelux** [comment]
Indeed you are correct. I didn't noticed before, but the strategy, originally written for SolarBeam, uses ISolarRouter as interface for Stella's router but the Interface is not 100% accurate. Some functions have the same name but they require different params. 

this is the router : https://moonscan.io/address/0xd0a01ec574d1fc6652edf79cb2f880fd47d34ab1#code

My strategy uses only 2 functions of the router:

- swapExactTokensForTokens -> works fine, with ISolarRouter

- getAmountsOut -> used in callReward only, doesn't work properly because the router wants different params from the ones the strategy gives it.


So overall The strategy works just fine, except  callReward. Should I redeploy fixing this ?

**Comment by sircryptomaxi** [comment]
Yes we need the callReward to work, please adjust and redeploy.

**Comment by lodelux** [comment]
deployed new contract and edited the first comment on this PR with correct addresses. Thank you @sircryptomaxi  for noticing my mistake.

**Comment by AllTradesz** [comment]
> the strategy, originally written for SolarBeam, uses ISolarRouter as interface for Stella's router but the Interface is not 100% accurate
> getAmountsOut -> used in callReward only, doesn't work properly because the router wants different params from the ones the strategy gives it.

@Iodelux, since you have your finger on this, could you also PR a fix for the template SolarBeam strategy or, perhaps more precisely, the ISolarRouter interface, so that this issue stops surfacing? It's been an irritant for us on Moonbeam for some time now.

**Comment by lodelux** [comment]
> 
Actually Stellaswap uses UniswapRouterETH and  the other strategies for Stellaswap on the repo use the correct interface. This one was a stableLP so I had to create a new strat. and I copied it from a Solarbeam one, forgetting to change the Router interface 
to the correct IUniswapRouterETH. Should I just PR my new StableLP strategy in the Stellaswap strategies folder ?

**Comment by AllTradesz** [comment]
> Should I just PR my new StableLP strategy in the Stellaswap strategies folder ?

I'll punt and let @sircryptomaxi answer this.  :)

**Comment by lodelux** [comment]
I deleted the previous comment by mistake, copy pasting it here again:



Actually Stellaswap uses UniswapRouterETH and the other strategies for Stellaswap on the repo use the correct interface. This one was a stableLP so I had to create a new strat. and I copied it from a Solarbeam one, forgetting to change the Router interface
to the correct IUniswapRouterETH. Should I just PR my new StableLP strategy in the Stellaswap strategies folder ?

**Comment by sircryptomaxi** [comment]
@lodelux yes please do open a PR to add the stable strat to the StellaSwap folder. Thank you for redeploying. 
@AllTradesz I don’t think the Solarbeam strat is the issue since it works for Solarbeam, the Solarflare and StellaSwap vaults need their own strat in the repo rather than reusing the Solarbeam one.

**Comment by AllTradesz** [comment]
> @AllTradesz I don’t think the Solarbeam strat is the issue since it works for Solarbeam
Actually `callReward` doesn't/hasn't worked on quite a few Solarbeam strats, but per @MirthFutures it wasn't worth redeploys to fix it, so I devved a workaround in cowllector to allow skipping of that check on affected strats.

**Pull request merged**
