### PR TITLE
Add Joe gOHM-FRAX Vault

### PR DESCRIPTION
**Pull request by Tburm**
Vault: [0x42b2713e4eDA3C2275CE28696709A35CeB98A8E4](https://snowtrace.io/address/0x42b2713e4eda3c2275ce28696709a35ceb98a8e4)
Strategy: [0xB0225E1c3BEd1aba89fa0c355de3941aC9FD6758](https://snowtrace.io/address/0xB0225E1c3BEd1aba89fa0c355de3941aC9FD6758)
Want: 0x3E6Be71dE004363379d864006AAC37C9F55F8329
PoolId: 34

### CODE REVIEW

**Comment by MirthFutures** [comment]
New vaults need to go on top under BIFI Maxi and any boosts. Can you move below the AVAX boost?

**Comment by Tburm** [comment]
@MirthFutures I updated the order

**Comment by MirthFutures** [comment]
@Tburm Call Rewards and Rewards Available are broken. Its because you used the wrong strategy. There is trader joe specific strategies.

**Comment by Tburm** [comment]
@MirthFutures I see, I will re-deploy with the TraderJoe strategy.

**Pull request closed without merging**
