### PR TITLE
Add pangolin LOOT-AVAX + MIM-USDC.e

### PR DESCRIPTION
**Pull request by pumpingGhost**
LOOT-AVAX (dual rewards PNG + LOOT)
Vault: 0x8e57f9B3f67Cdb371Ae707B7E618f4056579377f
Strategy: 0x3E7977aB38B18017c51027e4e35f029DDB54C2DB
Want: 0x1bFae75b28925BF4a5bf830c141EA29CB0A868F1
PoolId: 65

MIM-USDC.e
Vault: 0x83E05C8a4AdEfA875ABe0f30a18bb6F9b54b807e
Strategy: 0x06f77FA8AB2B26c9c0515d6FB41c31C158B2a40E
Want: 0xE75eD6E50e3e2dc6b06FAf38b943560BD22e343B
PoolId: 38

### CODE REVIEW

**Comment by roman-monk** [comment]
whats up with `callRewards` in LOOT strat? 
always 0, but rewardsAvailable not.

somehow you added 3 exactly same rewards to output records.

not critical but i think reward to native would be more optimal
there are 2 additional swaps, LOOT-**AVAX-PNG**, **PNG-AVAX**, each swap lose 0.3%.
but LOOT-AVAX would be enough.
of course fees should be charged from native token then.
it makes sense only if AVAX is more popular route than PNG, i think it might be the case.
for example we have such routs in QuickDual farms and in Geist

**Comment by pumpingGhost** [comment]
> whats up with `callRewards` in LOOT strat? always 0, but rewardsAvailable not.
> 
> somehow you added 3 exactly same rewards to output records.
> 
> not critical but i think reward to native would be more optimal there are 2 additional swaps, LOOT-**AVAX-PNG**, **PNG-AVAX**, each swap lose 0.3%. but LOOT-AVAX would be enough. of course fees should be charged from native token then. it makes sense only if AVAX is more popular route than PNG, i think it might be the case. for example we have such routs in QuickDual farms and in Geist

Yes, I noticed this too, the routing is not optimal when using the strat for multiple rewards. But the strategy is designed to be polymorph and work for both single reward and multi reward pools with the option to remove reward routes in order to transform a multi reward strat into a single reward strat without redeployment.
But I agree with you, reward to native would be the better choice for PNG.
If you want I can implement a separate strat dedicated to pangolin multi reward farms for future vaults.

**Comment by pumpingGhost** [comment]
@roman-monk I should have removed the latter routes. As you can see the rewardToOutput view does not decode the contents of the two-dimensional array correctly, so I tested different argument formats for the addRewardRoute() function. In the end, the routes have been properly set in all three calls, so the latter two can be removed. Could you please do this with the keeper?

**Comment by MirthFutures** [comment]
> @roman-monk I should have removed the latter routes. As you can see the rewardToOutput view does not decode the contents of the two-dimensional array correctly, so I tested different argument formats for the addRewardRoute() function. In the end, the routes have been properly set in all three calls, so the latter two can be removed. Could you please do this with the keeper?

Can't it's onlyOwner. That's why Kexley suggest making add and remove route functions onlyManager.

**Comment by pumpingGhost** [comment]
> > @roman-monk I should have removed the latter routes. As you can see the rewardToOutput view does not decode the contents of the two-dimensional array correctly, so I tested different argument formats for the addRewardRoute() function. In the end, the routes have been properly set in all three calls, so the latter two can be removed. Could you please do this with the keeper?
> 
> Can't it's onlyOwner. That's why Kexley suggested making add and remove route functions onlyManager.

So I suggest the following. I will implement a new strat to address both the onlyOwner and the route inefficiency problems. This new start would be oriented towards pangolin multi reward pools, including an appropriate constructor to set it up as multi reward strat from the get go.
I have one more Pangolin dual reward vault in the pipe anyway, so I'd bundle LOOT-AVAX with MONEY-AVAX in a new PR, once the new strat is approved by you, kexley or roman. 
If that sounds good to you, I will exclude LOOT-AVAX now from this PR, so we can ship MIM-USDC.e.
Please let me know.

**Pull request merged**
