### PR TITLE
Single Asset Addy vault (Adamant Finance)

### PR DESCRIPTION
**Pull request by Moonster-BSC**
Vault: 0x6b7c061949BE60d59F857fcc08b76c278c3B73C0
Strat: 0x90337ecE11Ac8fD538A47a8F9F1D04E29cA595af
Reward Pool (MultiFeeDistribution): 0x920f22E1e5da04504b765F8110ab96A20E6408Bd
want (ADDY): 0xc3FdbadC7c795EF1D6Ba111e06fF8F16A20Ea539

Verifications: 

strat:
https://explorer-mainnet.maticvigil.com/address/0x6b7c061949BE60d59F857fcc08b76c278c3B73C0/contracts
https://explorer-mainnet.maticvigil.com/address/0x90337ecE11Ac8fD538A47a8F9F1D04E29cA595af/contracts

### CODE REVIEW

**Comment by roman-monk** [comment]
@Moonster-BSC need to verify strat contract

**Comment by Moonster-BSC** [comment]
@roman-monk will have to redeploy. The contract verification option still isn't showing up on maticvigil

**Comment by Moonster-BSC** [comment]
Updated with verified strats

**Comment by roman-monk** [comment]
just a small concern, i don't see unpause event and tx, but the strat status is paused=false.
did you unpause it?

nit: maybe keep consistent name next time, like `StrategyAndy`

**Comment by Moonster-BSC** [comment]
Weird.

https://explorer-mainnet.maticvigil.com/tx/0x581ba632459109e43081ca1f3609151576a3c10c684f2fb7844d4cd0685df18c/internal-transactions

Says pending here.

image

Metamask says successfully confirmed. Maybe an issue with MaticVigil?

**Pull request merged**
