### PR TITLE
Add USDC-AVAX, PNG-USDC, PNG-AVAX

### PR DESCRIPTION
**Pull request by AABeely**
Deployed Vaults Below:

Deploying: Moo PangolinV2 USDC.e-AVAX
Vault: 0x9B02209a331c072637C6eBd34cdCD6b6A16987a9
Strategy: 0xE497A9B4761e5359BA1C8E68116BD979f2273896
Want: 0xbd918Ed441767fe7924e99F6a0E0B568ac1970D9
PoolId: 9

Deploying: Moo PangolinV2 PNG-AVAX
Vault: 0x180A73F4e0a84E4343019529429344cBEC21d946
Strategy: 0x87F322dD9c327B4F91A7D620EE6ED7FA883Af62f
Want: 0xd7538cABBf8605BdE1f4901B47B8D42c61DE0367
PoolId: 0

Deploying: Moo PangolinV2 PNG-USDC.e
Vault: 0x9829E51f6C1292563892dC65A4270b94E09B30C0
Strategy: 0x838CF719bd6c5536625306467b015a14f76c500B
Want: 0xC33Ac18900b2f63DFb60B554B1F53Cd5b474d4cd
PoolId: 1

### CODE REVIEW

**Comment by MirthFutures** [comment]
Resolve conflicts

**Comment by AABeely** [comment]
@MirthFutures Conflicts resolved.

**Comment by roman-monk** [comment]
Why did we lose this recommendation from @sircryptomaxi ?
https://github.com/beefyfinance/beefy-contracts/pull/148#discussion_r787735509
image

I see it was updated and then removed again

**Comment by AABeely** [comment]
@roman-monk In a previous review, I was told to copy the way Solarbeam contract worked in regards to the way optional dual rewards + setting and removal of reward routes worked. I've simply copied the route setting and removal functions directly out of the already accepted strategy

**Pull request merged**
