### PR TITLE
Add fantom vaults

### PR DESCRIPTION
**Pull request by pumpingGhost**
BASED-BSHARE
Vault: 0xaC16fd4821e1Bf39148c374f02874e642E6CB8FA
Strategy: 0xF58431c634759bC20793EBB67cce1671EB43E97d
Want: 0x5748b5Dd1f59342f85d170c48C427959c2f9f262
PoolId: 5 

God Between Two Stables
Vault: 0xCbc3A0ae73ba667d69f9023c2d11276E016a9C09
Strategy: 0x62159EAae3Cec9a447AEf1d0400c8596AC9FDA27
ChefPoolId: 67
WantPoolId: 0x8b858eaf095a7337de6f9bc212993338773ca34e00020000000000000000023c

Exploding Shrapnel
Vault: 0xE480703dD6959D997359B675B7b2C008f8778e5a
Strategy: 0x7f7Fb573CBdbc2a7E349E5184bC39fB8eAEB88ce
ChefPoolId: 50
WantPoolId: 0x8fdd16a23aebe95b928f1863760618e9ec29e72d000100000000000000000166

Boomer Beets
Vault: 0x19D1c824b2CAC7494095C112c6f98823Bcfc9F3f
Strategy: 0xceb6d118640FF21ED47de296669Ba7A74752942b
ChefPoolId: 62
WantPoolId: 0x8fdd16a23aebe95b928f1863760618e9ec29e72d000100000000000000000166

### CODE REVIEW

**Comment by pumpingGhost** [comment]
> Why not just swap BSHARE to BASED for LP1 instead of 4 token route?

Because the other route has way deeper liquidity. 
Swapping just 5 BSHARE to BASED has over 4% price impact.

**Comment by MirthFutures** [comment]
There is $500K liquidity? Swapping through the pair makes way more sense. If there is not enough liquidity through the pair we shouldnt vault it.

**Comment by pumpingGhost** [comment]
> There is $500K liquidity? Swapping through the pair makes way more sense. If there is not enough liquidity through the pair we shouldnt vault it.

Yeah I see your point. The 4 token route would pay off at a high vault TVL, but in the beginning it won't outweigh the 3x slippage.
I'll just redeploy it with the direct route.

**Comment by pumpingGhost** [comment]
New strategy: StrategyBeethovenxSpiritRouter (https://github.com/beefyfinance/beefy-contracts/pull/172)

Beethoven X recently launched farms with reward tokens that don't have proper liquidity on their side.
"One God Between Two Stables" is one such farms and rewards in BEETS + DEUS.
DEUS however can only be swapped over community pools with very low liquidity.
This raised the need for a new strategy that utilizes a second DEX that supports the respective reward token.
StrategyBeethovenxSpiritRouter uses both the Beethoven X(for Beets) and SpiritSwap(for DEUS) routers to swap all rewards for native. Then after subtracting the fees, native is swapped for input again using the SpiritSwap routes, which provides deep liquidity for the DEUS-DEI pair.

This strategy can potentially be reused for future dual reward farms that suffer from a similar problem.

**Comment by MirthFutures** [comment]
All beethovenX strats have callReward as a write function instead a view function. This will not align with whats needed for our cowllector, they will need to be redeployed.

**Pull request merged**
